version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:password@db/financial_accounting_system
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=financial_accounting_system
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: