"""Initial migration

Revision ID: 68e534dad8c6
Revises: 
Create Date: 2025-03-13 18:45:09.724475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e534dad8c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('invoices',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('receiver', sa.String(length=255), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('invoice_type', sa.Enum('Service Invoice', 'Stock Purchase Invoice', 'Real Estate Purchase Invoice', 'Equipment Purchase Invoice', 'Raw Materials Purchase Invoice', 'Salary Invoice', name='invoice_types'), nullable=False),
    sa.Column('status', sa.Enum('Paid', 'Unpaid', 'Pending', 'Cancelled'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_table('LineItem',
    sa.Column('line_item_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('line_item_id')
    )
    op.create_table('ledger_entries',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('debit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('entry_date', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_entries')
    op.drop_table('LineItem')
    op.drop_table('invoices')
    op.drop_table('companies')
    # ### end Alembic commands ###
